version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  app:
    image: finance-module-poc
    build:
      context: .
      dockerfile: .docker/Dockerfile
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 8080:80
    volumes:
      - .:/opt/finance-module-poc
